-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJJgizkZPTBz5trxr
M+AMq3rztcoXFlC/RPXsJ8gUkk2gCgYIKoZIzj0DAQehRANCAASAQEvanKdBvAqr
E98X9SekAOi5KkSdv8plV+Qq4LrS2p1Xy+txiHFTQhkm4yLpZrjfUcttMO+t5dow
2LlFXq3e
-----END PRIVATE KEY-----