-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg+UO7+hKBEwgZjwzV
8+D2aAIC0Synt7HDoW5fgUgjnN2gCgYIKoZIzj0DAQehRANCAASApLifjLkOIbtM
DgGzu42EFoibKIlFx8R0T8CcCVN2B0OiZ7dP7npdGZpCpXnFTV3PLxLRg2AvjRQS
gIl3mPYp
-----END PRIVATE KEY-----