-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdcDJySyQjGHFfIpS
jzBTG5+m9bCr0Y1ZoqqZe29UA/mgCgYIKoZIzj0DAQehRANCAAT3tp0njgPcn4DF
GgIQeeGCx4TqvGrd+jASHVN0CRyWPZOwvFNxF9Q2U+LfG3gYmHdMa0plDlCxCOyt
9JxVUxUm
-----END PRIVATE KEY-----